### PR TITLE
Update `@actions/core` and node version

### LINKED ISSUE #4: Update to Node 16
I'm getting a deprecation notice that kamranayub/wait-for-netlify-action needs to be updated to use Node 16.

>Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

### LINKED ISSUE #5: Use environment files instead of `set-output::`
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### PR DESCRIPTION
**Pull request by jasikpark**
This fixes #5 and fixes #4

### CODE REVIEW

**Comment by IanVS** [comment]
@kamranayub just a friendly ping in case you don't get a notification.

**Review by kamranayub — APPROVED** [review]
I assume the looser match is to widen support so LGTM.

**Comment by kamranayub** [comment]
Thanks @jasikpark and @IanVS 

I'm going to slap a hacktoberfest label on here once I am able to. 

Also looks like I need to refresh npm token

**Pull request merged**
